apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 8088
    targetPort: 8088
    name: smtp
    port: 2525
    targetPort: 2525
  selector:
    io.kompose.service: notification-service
status:
  loadBalancer: {}
