pipeline:
  build_docker_image:
    image: docker:17.09.0-ce
    privileged: false
    when:
      branch: [master, develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ./docker-build.sh egar-notification-service
  image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    privileged: false
    when:
      branch: [master, develop]
    environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ./docker-deploy.sh egar-notification-service
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/$(SLACK_WEBHOOK)
    channel: builds
    when:
      status: [success, failure]
